// <auto-generated />
using System;
using Kutuphane.DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kutuphane.DataAccess.Migrations
{
    [DbContext(typeof(KutuphaneDbContext))]
    [Migration("20201226103541_KutuphaneDbContet")]
    partial class KutuphaneDbContet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Emanet", b =>
                {
                    b.Property<int>("emanetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmanetGeriAlmaTarih")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmanetIslemTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmanetTeslimEdildi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmanetVermeTarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("kitapNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("kitapNo1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ogrenciNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ogrenciNo1")
                        .HasColumnType("INTEGER");

                    b.HasKey("emanetNo");

                    b.HasIndex("kitapNo1");

                    b.HasIndex("ogrenciNo1");

                    b.ToTable("emanets");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Kitap", b =>
                {
                    b.Property<int>("kitapNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("kitapAd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("kitapRaftami")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kitapSayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kitapYazari")
                        .HasColumnType("TEXT");

                    b.HasKey("kitapNo");

                    b.ToTable("kitaps");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Kullanıcı", b =>
                {
                    b.Property<int>("KullanıcıID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("k_ogrenciNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kullanıcıPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("kullanıcıUserName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ogrenciNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("KullanıcıID");

                    b.HasIndex("ogrenciNo");

                    b.ToTable("kullanıcıs");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Ogrenci", b =>
                {
                    b.Property<int>("ogrenciNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ogrenciAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciNumarası")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciTelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("ogrenciNo");

                    b.ToTable("ogrencis");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Emanet", b =>
                {
                    b.HasOne("Kutuphane.Entities.Concrete.Kitap", null)
                        .WithMany("Emanets")
                        .HasForeignKey("kitapNo1");

                    b.HasOne("Kutuphane.Entities.Concrete.Ogrenci", null)
                        .WithMany("Emanets")
                        .HasForeignKey("ogrenciNo1");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Kullanıcı", b =>
                {
                    b.HasOne("Kutuphane.Entities.Concrete.Ogrenci", null)
                        .WithMany("Kullanıcıs")
                        .HasForeignKey("ogrenciNo");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Kitap", b =>
                {
                    b.Navigation("Emanets");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Ogrenci", b =>
                {
                    b.Navigation("Emanets");

                    b.Navigation("Kullanıcıs");
                });
#pragma warning restore 612, 618
        }
    }
}
