// <auto-generated />
using System;
using Kutuphane.DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kutuphane.DataAccess.Migrations
{
    [DbContext(typeof(KutuphaneDbContext))]
    [Migration("20201227100515_Denso")]
    partial class Denso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Emanet", b =>
                {
                    b.Property<int>("emanetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmanetGeriAlmaTarih")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmanetIslemTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmanetTeslimEdildi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmanetVermeTarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("emanetNo");

                    b.HasIndex("KitapId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Emanet");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("kitapAd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("kitapRaftami")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kitapSayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kitapYazari")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kitap");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ogrenciAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciNumarası")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciSifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("ogrenciTelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ogrenci");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Emanet", b =>
                {
                    b.HasOne("Kutuphane.Entities.Concrete.Kitap", "Kitap")
                        .WithMany("Emanet")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Entities.Concrete.Ogrenci", "Ogrenci")
                        .WithMany("Emanet")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Kitap", b =>
                {
                    b.Navigation("Emanet");
                });

            modelBuilder.Entity("Kutuphane.Entities.Concrete.Ogrenci", b =>
                {
                    b.Navigation("Emanet");
                });
#pragma warning restore 612, 618
        }
    }
}
